version: '3.3'
services:
  ifg-postgresql:
    image: postgres:15.1
    container_name: hexagonal-java-db
    ports:
      - 5555:5432
    environment:
      - POSTGRES_DB=hexagonal
      - POSTGRES_USER=hexagonal
      - POSTGRES_PASSWORD=hexagonal