spring:
  datasource:
    name: hexagonal
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/hexagonal
    username: hexagonal
    password: hexagonal
  jpa:
    properties:
      hibernate:
        default_schema: hexagonal
  flyway:
    create-schemas: true
    schemas: ${spring.datasource.name}
server:
  port: 8083
  servlet:
    context-path: /hexagonal